data_ingestion:
  bucket_name: "mlops_gcp_data"
  source_directory: "raw_data/"
  bucket_file_name: "Hotel_Reservations.csv"
  file_types:
    - ".csv"
  train_ratio: .8
data_processing:
  categorical_features:
    - type_of_meal_plan
    - room_type_reserved
    - market_segment_type
    - booking_status
  numerical_features:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - required_car_parking_space
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - repeated_guest
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
  target: "booking_status"  
  skewness_threshold: 0.5  
  no_of_features: 10
  missing_value_strategy: "mean_imputation"
  categorical_encoding: "target_encoding"
  target_column: "booking_status"
  test_size: 0.2
  random_state: 42  
mlflow:
  experiment_name: "lightgbm_model_v1.0"
  run_name: "model_training_v1"

